const express = require('express')
const User = express.Router()
const {createUser,userLogin,verifyUser,forgotpassword, resetpassword,protected,changepass,logout,FindUser} = require('../Controllers/userControllers.js')
User.route('/signup').post(createUser)
User.route('/login').post(userLogin)
User.route('/verify').get(verifyUser)
User.route('/forgotpass').post(forgotpassword)
User.route('/resetpass/:token').patch(resetpassword)
User.route('/updatepass').patch(protected,changepass)
User.route('/logout').get(logout)
User.route('/finduser').post(FindUser)
module.exports = User